services:
  aos-ssh:
    image: docker.io/foricher/ale-aos-ssh:1.0.0
    ports:
      - "8210:8110"
    volumes:
      - ./data:/app/data
  aos-mcp:
    image: docker.io/foricher/ale-aos-mcp:1.0.0
    ports:
      - "8000:8000"
    environment:
      - AOS_SSH_URL=http://aos-ssh:8110
      - MCP_TRANSPORT=streamable-http
#      - MCP_TRANSPORT=sse
    volumes:
      - ./data:/app/data
    depends_on:
      - aos-ssh